version: '3'

services:
  mongo:
    image: mongo

  redis:
    image: redis

  backend:
    build:
      context: ./backend
    ports:
      - '3662:3002'
    depends_on:
      - redis
      - mongo
