version: '3'

services:
  mongo:
    image: mongo
    container_name: fuongz__hiip-devtools__mongo

  redis:
    image: redis
    container_name: fuongz__hiip-devtools__redis

  frontend:
    build:
      context: ./frontend
    container_name: fuongz__hiip-devtools__frontend
    ports:
      - 3661:8000
    env_file:
      - ./.env.frontend

  backend:
    build:
      context: ./backend
    container_name: fuongz__hiip-devtools__backend
    env_file:
      - ./.env.backend
    depends_on:
      - redis
      - mongo
